import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs';
const $=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cards=JSON.parse(localStorage.getItem('dentanki.cards')||'[]'), attempts=JSON.parse(localStorage.getItem('dentanki.attempts')||'[]'), queue=[], current=null, selected='', startedAt=0, sb=null, user=null, ocrWorker=null, cancelRequested=false;
const save=()=>{localStorage.setItem('dentanki.cards',JSON.stringify(cards));localStorage.setItem('dentanki.attempts',JSON.stringify(attempts));refresh();syncPush()};
const now=()=>new Date().toISOString(), due=c=>!c.nextReview||new Date(c.nextReview)<=new Date();
function schedule(c,grade){const intervals=[0,1,3,7,14,30,60,120];c.level=Math.max(0,Math.min(intervals.length-1,(c.level||0)+(grade?1:-1)));const d=new Date();d.setDate(d.getDate()+intervals[c.level]);c.nextReview=d.toISOString();}
function tabs(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');refresh()})}
function cleanCanvas(c,mode){if(mode==='none'||mode==='annotations')return c;const ctx=c.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,c.width,c.height),d=img.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx-mn,lum=.299*r+.587*g+.114*b;if(mode==='color'&&sat>28&&mx>70){d[i]=d[i+1]=d[i+2]=255;continue}if(mode==='strong'){if(sat>22&&mx>60){d[i]=d[i+1]=d[i+2]=255;continue}const v=lum>210?255:lum<150?0:Math.round((lum-150)/60*255);d[i]=d[i+1]=d[i+2]=v}}ctx.putImageData(img,0,0);return c}
async function renderPageCanvas(page,scale=.7,cleanupMode='annotations'){const vp=page.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:vp,annotationMode:cleanupMode==='none'?pdfjsLib.AnnotationMode.ENABLE:pdfjsLib.AnnotationMode.DISABLE}).promise;return cleanCanvas(c,cleanupMode)}
async function pageImage(page,cleanupMode){const c=await renderPageCanvas(page,.7,cleanupMode);return c.toDataURL('image/jpeg',.7)}
function logOCR(message){const el=$('#ocrLog');el.textContent+=(el.textContent?'\n':'')+message;el.scrollTop=el.scrollHeight}
async function getOCRWorker(){if(ocrWorker)return ocrWorker;if(!window.Tesseract)throw new Error('OCRライブラリを読み込めませんでした。通信状態を確認してください。');logOCR('日本語OCRエンジンを準備しています…');ocrWorker=await Tesseract.createWorker('jpn+eng',1,{logger:m=>{if(m.status==='recognizing text'){$('#status').textContent=`OCR処理中：${Math.round((m.progress||0)*100)}%`}}});return ocrWorker}
async function extractText(page,mode,scale,fileName,pageNo,cleanupMode){const tc=await page.getTextContent();const embedded=tc.items.map(i=>i.str).join(' ').replace(/\s+/g,' ').trim();const needsOCR=mode==='always'||(mode==='auto'&&embedded.replace(/\s/g,'').length<30);if(!needsOCR)return{ text:embedded, method:'文字情報' };if(mode==='never')return{ text:embedded, method:'文字情報' };logOCR(`${fileName} ${pageNo}頁：OCR開始`);const canvas=await renderPageCanvas(page,scale,cleanupMode);const worker=await getOCRWorker();const result=await worker.recognize(canvas);const text=(result.data.text||'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();logOCR(`${fileName} ${pageNo}頁：OCR完了（${text.length}文字）`);canvas.width=1;canvas.height=1;return{ text, method:'OCR' }}
function parseChoices(text){const ls=text.split(/\n/),choices=[],body=[];for(const l of ls){const m=l.trim().match(/^([A-Ea-e]|[1-9]|[ア-オ])[.．、)）:]\s*(.+)$/);m?choices.push(m[2]):body.push(l)}return{body:body.join('\n').trim(),choices}}
function splitQuestions(raw){const t=raw.replace(/\r/g,'').replace(/(問\s*\d+|(?:^|\n)\s*\d+[.．、]|[（(]\d+[）)])/g,'\n$1').replace(/\n{3,}/g,'\n\n');let parts=t.split(/\n(?=問\s*\d+|\s*\d+[.．、]|[（(]\d+[）)])/).map(x=>x.trim()).filter(x=>x.length>20);if(!parts.length&&t.trim().length>20)parts=[t.trim()];return parts}
$('#cancelExtract').onclick=()=>{cancelRequested=true;$('#status').textContent='中止処理中…'};
$('#extractBtn').onclick=async()=>{const fs=[...$('#pdfInput').files];if(!fs.length)return alert('PDFを選択してください');cancelRequested=false;$('#cancelExtract').hidden=false;$('#extractBtn').disabled=true;$('#ocrLog').textContent='';let finishedPages=0,totalPages=0,added=0;try{const loaded=[];for(const f of fs){const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;loaded.push({f,pdf});totalPages+=pdf.numPages}for(const {f,pdf} of loaded){for(let p=1;p<=pdf.numPages;p++){if(cancelRequested)throw new Error('USER_CANCELLED');$('#status').textContent=`解析中：${f.name} ${p}/${pdf.numPages}頁`;const page=await pdf.getPage(p);const cleanupMode=$('#cleanupMode').value;const annotations=cleanupMode==='none'?[]:await page.getAnnotations({intent:'display'});if(annotations.length)logOCR(`${f.name} ${p}頁：PDF注釈 ${annotations.length}件を除外`);const {text,method}=await extractText(page,$('#ocrMode').value,Number($('#ocrScale').value),f.name,p,cleanupMode);const parts=splitQuestions(text);if(parts.length){const image=await pageImage(page,cleanupMode);for(const part of parts){const q=parseChoices(part);cards.push({id:crypto.randomUUID(),text:q.body,choices:q.choices,answer:'',explanation:'',subject:$('#importSubject').value||'未分類',tags:$('#importTags').value.split(',').map(x=>x.trim()).filter(Boolean),favorite:false,source:f.name,page:p,image,extractionMethod:method,correct:0,wrong:0,level:0,nextReview:now(),createdAt:now(),updatedAt:now()});added++}}finishedPages++;$('#progress').value=finishedPages/totalPages*100;await new Promise(r=>setTimeout(r,0))}}save();$('#status').textContent=`抽出完了：${added}件。問題一覧で内容と正答を確認してください。`}catch(e){if(e.message==='USER_CANCELLED'){$('#status').textContent=`処理を中止しました。抽出済み${added}件は保存しました。`;save()}else{console.error(e);$('#status').textContent='エラー：'+e.message;alert('PDF解析中にエラーが発生しました：'+e.message)}}finally{$('#cancelExtract').hidden=true;$('#extractBtn').disabled=false}};
function renderCards(){const q=$('#search').value.toLowerCase(),sub=$('#subjectFilter').value,fil=$('#cardFilter').value;const list=cards.filter(c=>(!q||(c.text+' '+c.tags.join(' ')).toLowerCase().includes(q))&&(!sub||c.subject===sub)&&(fil==='all'||fil==='wrong'&&c.wrong>0||fil==='favorite'&&c.favorite||fil==='due'&&due(c)));$('#cardList').innerHTML=list.map(c=>`<article class="question"><div class="meta">${esc(c.subject)}・${esc(c.source||'手動')} ${c.page?'/ '+c.page+'頁':''}　正${c.correct} 誤${c.wrong}</div><h3>${esc(c.text)}</h3>${(c.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<div class="actions"><button onclick="editCard('${c.id}')">編集</button><button onclick="toggleFav('${c.id}')">${c.favorite?'★':'☆'}</button><button onclick="deleteCard('${c.id}')">削除</button></div></article>`).join('')||'<div class="card">該当する問題はありません。</div>'}
window.editCard=id=>{const c=cards.find(x=>x.id===id)||{id:'',text:'',choices:[],answer:'',explanation:'',subject:'',tags:[],favorite:false};$('#editId').value=c.id;$('#editText').value=c.text;$('#editChoices').value=(c.choices||[]).join('\n');$('#editAnswer').value=c.answer;$('#editExplanation').value=c.explanation;$('#editSubject').value=c.subject;$('#editTags').value=(c.tags||[]).join(',');$('#editFavorite').checked=c.favorite;$('#editDialog').showModal()};
window.toggleFav=id=>{const c=cards.find(x=>x.id===id);c.favorite=!c.favorite;c.updatedAt=now();save()};window.deleteCard=id=>{if(confirm('削除しますか？')){cards=cards.filter(x=>x.id!==id);save()}};$('#newCard').onclick=()=>editCard('');$('#cancelEdit').onclick=()=>$('#editDialog').close();$('#editForm').onsubmit=e=>{e.preventDefault();let c=cards.find(x=>x.id===$('#editId').value);if(!c){c={id:crypto.randomUUID(),correct:0,wrong:0,level:0,nextReview:now(),createdAt:now(),image:'',source:'手動'};cards.push(c)}Object.assign(c,{text:$('#editText').value,choices:$('#editChoices').value.split('\n').filter(Boolean),answer:$('#editAnswer').value.trim(),explanation:$('#editExplanation').value,subject:$('#editSubject').value||'未分類',tags:$('#editTags').value.split(',').map(x=>x.trim()).filter(Boolean),favorite:$('#editFavorite').checked,updatedAt:now()});$('#editDialog').close();save()};
$('#search').oninput=renderCards;$('#subjectFilter').onchange=renderCards;$('#cardFilter').onchange=renderCards;
function begin(mode=$('#studyMode').value){const sub=$('#studySubject').value;queue=cards.filter(c=>(!sub||c.subject===sub)&&(mode==='all'||mode==='due'&&due(c)||mode==='wrong'&&c.wrong>0||mode==='favorite'&&c.favorite||mode==='exam')).sort(()=>Math.random()-.5);if(mode==='exam')queue=queue.slice(0,100);next()}
$('#startStudy').onclick=()=>begin();$('#studyDue').onclick=()=>{document.querySelector('[data-tab="study"]').click();$('#studyMode').value='due';begin('due')};
function next(){selected='';current=queue.shift();startedAt=Date.now();if(!current){$('#quizCard').innerHTML='<h2>学習終了</h2><p>お疲れさまでした。</p>';return}$('#quizCard').innerHTML=`<div class="meta">${esc(current.subject)}　残り${queue.length}</div><h2>${esc(current.text)}</h2>${current.image?`<img class="quiz-image" src="${current.image}">`:''}${(current.choices||[]).map((x,i)=>`<button class="choice" data-a="${i+1}">${i+1}. ${esc(x)}</button>`).join('')||'<input id="free" placeholder="回答を入力">'}<button id="judge" class="primary">回答する</button><div id="result"></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.a});$('#judge').onclick=judge}
function judge(){const a=selected||($('#free')?.value||'').trim();if(!a)return alert('回答してください');const ok=String(a).toLowerCase()===String(current.answer).trim().toLowerCase()&&current.answer!=='';ok?current.correct++:current.wrong++;schedule(current,ok);current.updatedAt=now();attempts.push({id:crypto.randomUUID(),cardId:current.id,correct:ok,answeredAt:now(),seconds:Math.max(1,Math.round((Date.now()-startedAt)/1000)),subject:current.subject});save();$('#judge').disabled=true;$('#result').innerHTML=`<p class="${ok?'good':'bad'}">${ok?'正解':'不正解'}　正答：${esc(current.answer||'未登録')}</p><p>${esc(current.explanation||'解説未登録')}</p><button id="next">次へ</button>`;$('#next').onclick=next}
function refresh(){const subjects=[...new Set(cards.map(c=>c.subject))].sort();for(const id of ['subjectFilter','studySubject']){const el=$(id.startsWith('#')?id:'#'+id);const v=el.value;el.innerHTML=`<option value="">全科目</option>`+subjects.map(s=>`<option>${esc(s)}</option>`).join('');el.value=v}$('#totalCount').textContent=cards.length;$('#wrongCount').textContent=cards.filter(c=>c.wrong>0).length;$('#dueCount').textContent=cards.filter(due).length;const today=new Date().toISOString().slice(0,10),ta=attempts.filter(a=>a.answeredAt.startsWith(today));$('#todayCount').textContent=ta.length;$('#answersTotal').textContent=attempts.length;$('#accuracy').textContent=(attempts.length?Math.round(attempts.filter(a=>a.correct).length/attempts.length*100):0)+'%';$('#studyTime').textContent=Math.round(attempts.reduce((s,a)=>s+(a.seconds||0),0)/60)+'分';const days=new Set(attempts.map(a=>a.answeredAt.slice(0,10)));let st=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){st++;d.setDate(d.getDate()-1)}$('#streak').textContent=st+'日';$('#subjectSummary').innerHTML=subjects.map(s=>`<p><b>${esc(s)}</b>　${cards.filter(c=>c.subject===s).length}問</p>`).join('')||'未登録';$('#weakList').innerHTML=[...cards].filter(c=>c.wrong).sort((a,b)=>b.wrong-a.wrong).slice(0,10).map(c=>`<p><b>誤${c.wrong}</b> ${esc(c.text.slice(0,70))}</p>`).join('')||'誤答なし';renderCards();drawChart()}
function drawChart(){const c=$('#chart'),x=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=180*devicePixelRatio;x.clearRect(0,0,w,h);const arr=[];for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);arr.push(attempts.filter(a=>a.answeredAt.startsWith(k)).length)}const m=Math.max(1,...arr),bw=w/14;x.fillStyle='#0f766e';arr.forEach((v,i)=>x.fillRect(i*bw+4,h-(v/m)*(h-20),bw-8,(v/m)*(h-20)))}
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({cards,attempts})],{type:'application/json'}));a.download='dentanki-backup.json';a.click()};$('#importBackup').onchange=async e=>{const d=JSON.parse(await e.target.files[0].text());cards=d.cards||[];attempts=d.attempts||[];save()};$('#clearBtn').onclick=()=>{if(confirm('全データを削除しますか？')){cards=[];attempts=[];save()}};
function initCloud(){const u=localStorage.getItem('dentanki.supabaseUrl'),k=localStorage.getItem('dentanki.supabaseKey');if(u&&k){sb=supabase.createClient(u,k);sb.auth.getUser().then(r=>{user=r.data.user;syncPull()})}}$('#saveCloud').onclick=()=>{localStorage.setItem('dentanki.supabaseUrl',$('#supabaseUrl').value);localStorage.setItem('dentanki.supabaseKey',$('#supabaseKey').value);location.reload()};$('#login').onclick=async()=>{if(!sb)return alert('接続設定を保存してください');const {error}=await sb.auth.signInWithOtp({email:$('#email').value,options:{emailRedirectTo:location.href}});alert(error?error.message:'ログインリンクを送信しました')};$('#logout').onclick=async()=>{await sb?.auth.signOut();user=null;$('#syncBadge').textContent='ローカル'};
async function syncPull(){if(!sb)return;const {data:{user:u}}=await sb.auth.getUser();if(!u)return;user=u;$('#syncBadge').textContent='同期中';const [{data:c},{data:a}]=await Promise.all([sb.from('cards').select('*'),sb.from('attempts').select('*')]);if(c){const map=new Map(cards.map(x=>[x.id,x]));c.forEach(r=>map.set(r.id,r.data));cards=[...map.values()]}if(a){const map=new Map(attempts.map(x=>[x.id,x]));a.forEach(r=>map.set(r.id,r.data));attempts=[...map.values()]}localStorage.setItem('dentanki.cards',JSON.stringify(cards));localStorage.setItem('dentanki.attempts',JSON.stringify(attempts));$('#syncBadge').textContent='同期済み';refresh()}
let syncTimer;function syncPush(){clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{if(!sb||!user)return;$('#syncBadge').textContent='同期中';await Promise.all([sb.from('cards').upsert(cards.map(x=>({id:x.id,user_id:user.id,data:x,updated_at:x.updatedAt||now()}))),sb.from('attempts').upsert(attempts.map(x=>({id:x.id,user_id:user.id,data:x,updated_at:x.answeredAt||now()})))]);$('#syncBadge').textContent='同期済み'},800)}
$('#saveAI').onclick=()=>{localStorage.setItem('dentanki.aiEndpoint',$('#aiEndpoint').value);alert('保存しました')};
tabs();$('#supabaseUrl').value=localStorage.getItem('dentanki.supabaseUrl')||'';$('#supabaseKey').value=localStorage.getItem('dentanki.supabaseKey')||'';$('#aiEndpoint').value=localStorage.getItem('dentanki.aiEndpoint')||'';initCloud();refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
